AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  s3bucketname:
    Type: String
    Description: The s3 bucket to deploy to.

Resources:
  BookADeskUiS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName:
        Ref: s3bucketname
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html #TODO: how will we create this file?
