AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SHA1:
    Type: String
    Default: "852b4282477288b9ef6436a4b1b146c0f7693e65"
  S3Bucket:
    Type: String
    Description: The s3 bucket to deploy to.

Resources:
  BookADeskUiS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref S3Bucket
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html #TODO: how will we create this file?
