AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SHA1:
    Type: String
  s3bucketname:
    Type: String
    Description: The s3 bucket to deploy to.

Resources:
  BookADeskUiS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName:
        Ref: s3bucketname
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html #TODO: how will we create this file?
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName: !Sub "${s3bucketname}.s3.${AWS::Region}.amazonaws.com"
            Id: broadsign-platform-shell-s3
            OriginPath: !Sub "/${SHA1}"
        DefaultCacheBehavior:
          MinTTL: 0
          Compress: true
          TargetOriginId: book-a-desk-ui
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
