AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SHA1:
    Type: String
    Default: "b6218d35b915bad1d2826c6880e893be4054631f"
  S3Bucket:
    Type: String
    Description: The s3 bucket to deploy to.
  CertificateID:
    Type: String
    Description: AWS Certificate Id
  Alias:
    Type: String
    Description: domain name alias
  HostedZoneID:
    Type: String
    Description: Id of DNS hosted zone

Resources:
  BookADeskUiS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref S3Bucket
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html #TODO: how will we create this file?
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName: !Sub "${S3Bucket}.s3.${AWS::Region}.amazonaws.com"
            Id: book-a-desk-ui-s3
            OriginPath: !Sub "/${SHA1}"
        DefaultCacheBehavior:
          MinTTL: 0
          Compress: true
          TargetOriginId: book-a-desk-ui-s3
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        Aliases:
          - !Sub "${Alias}"
        ViewerCertificate:
          AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CertificateID}"
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
