AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Env:
    Type: String
    Description: The environment you're deploying to.

Resources:
  BookADeskUiS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: book-a-desk-ui-${Env}
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html #TODO: how will we create this file?
