user name: book-a-desk

exception: book-a-desk-dev in dev account

permissions:
- AmazonDynamoDBFullAccess
- AWSCertificateManagerReadOnly
- AWSCloudFormationFullAccess
- CloudFrontFullAccess
- AmazonEC2ContainerRegistryFullAccess
- GetParametersByPath
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
            "ssm:GetParametersByPath"
        ],
        "Resource": "*"
      }
    ]
  }
- PassRole:
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "VisualEditor0",
        "Effect": "Allow",
        "Action": "iam:PassRole",
        "Resource": [
          "<arn-of-cloudformation-role>",
          "<arn-of-cloudformation-role>"
        ]
      }
    ]
  }
    
Cloudformationrole:
  - AmazonS3FullAccess
  - CloudFrontFullAccess
    
Cloudformationbackendrole:
  - IAMFullAccess
  - CloudWatchFullAccess
  - AmazonECS_FullAccess
  - AWSCertificateManagerReadOnly
  - AmazonRoute53FullAccess
  - AmazonEC2FullAccess