user name: book-a-desk

exception: book-a-desk-dev in dev account

permissions:
- AmazonDynamoDBFullAccess
- AWSCertificateManagerReadOnly
- AWSCloudFormationFullAccess
- CloudFrontFullAccess
- GetParametersByPath
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
            "ssm:GetParametersByPath"
        ],
        "Resource": "*"
      }
    ]
  }