exception: book-a-desk-dev in dev account

user: book-a-desk-ui

permissions:
- AWSCloudFormationFullAccess
- AmazonS3FullAccess
- AmazonEC2ContainerRegistryFullAccess
  
user: book-a-desk-backend

permissions:
- AmazonDynamoDBFullAccess
- AWSCloudFormationFullAccess
- AmazonEC2ContainerRegistryFullAccess
- GetParametersByPath
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
            "ssm:GetParametersByPath"
        ],
        "Resource": "*"
      }
    ]
  }
- PassRole:
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "VisualEditor0",
        "Effect": "Allow",
        "Action": "iam:PassRole",
        "Resource": [
          "<arn-of-cloudformation-role>",
          "<arn-of-cloudformation-role>"
        ]
      }
    ]
  }
    
cloudformationstack<env>:
  - AmazonS3FullAccess
  - CloudFrontFullAccess
  - AmazonRoute53FullAccess
    
cloudformationstackbackend<env>:
  - IAMFullAccess
  - CloudWatchFullAccess
  - AmazonECS_FullAccess
  - AWSCertificateManagerReadOnly
  - AmazonRoute53FullAccess
  - AmazonEC2FullAccess