version: 2.1

orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.0
  aws-s3: circleci/aws-s3@1.0.16
  
parameters:
  s3-bucket-dev:
      type: string
      default: book-a-desk-ui-2
  acm-certificate-id-dev:
      type: string
      default: 50d2e84d-f1f3-47e0-af7a-82724b817877
  s3-bucket-test:
      type: string
      default: book-a-desk-ui-test
  acm-certificate-id-test:
      type: string
      default: 34a7387f-bb56-42d0-8523-e56ee56a0522
      
commands:
  authenticate-aws-book-a-desk-dev:
    description: "Configure AWS credentials for Book A Desk Dev"
    steps:
      - run:
          name: "Initialize BASH_ENV variables"
          command: |
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEV}" >> $BASH_ENV
            
  aws-cloudformation-deploy:
    parameters:
      update-cdn:
        type: boolean
        default: false
      authenticate-aws:
        type: steps
      s3-bucket-name:
        type: string
      certificate-id:
        type: string
      environment:
        type: string
    steps:
      - steps: << parameters.authenticate-aws >>
      - run:
          name: Ensure infrastructure is up to date <<# parameters.update-cdn >>and update the CDN origin<</ parameters.update-cdn >>
          command: |
            aws cloudformation deploy \
              --parameter-overrides "S3Bucket=<< parameters.s3-bucket-name >>" "CertificateID=<< parameters.certificate-id >>" "Environment=<< parameters.environment >>" <<# parameters.update-cdn >>"SHA1=${CIRCLE_SHA1}"<</ parameters.update-cdn >> \
              --stack-name book-a-desk-ui \
              --template-file ./infra/cf.yaml \
              --capabilities CAPABILITY_NAMED_IAM
  

jobs:
  build-and-unit-test:
    docker:
      - image: cimg/node:15.8.0
    parameters:
      api-url:
        type: string
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Unit test
          command: npm run test:unit:ci
          environment:
            JEST_JUNIT_OUTPUT_NAME: ./reports/unit-tests.xml
      - run:
          name: Build
          command: |
            export VUE_APP_BASE_API_URL=<< parameters.api-url >>
            npm run build
      - store_test_results:
          path: ./reports/
      - persist_to_workspace:
          root: ./dist
          paths:
            - ./*

  deploy-cloudformation:
    executor: aws-cli/default
    parameters:
      update-cdn:
        type: boolean
        default: false
      authenticate-aws:
        type: steps
      s3-bucket-name:
        type: string
      certificate-id:
        type: string
      environment:
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
      - aws-cloudformation-deploy:
          update-cdn: << parameters.update-cdn >>
          authenticate-aws: << parameters.authenticate-aws >>
          s3-bucket-name: << parameters.s3-bucket-name >>
          certificate-id: << parameters.certificate-id >>
          environment: << parameters.environment >>
          
  publish-to-s3:
    docker:
      - image: cimg/python:3.6
    parameters:
      destination-path:
        type: string
      s3-bucket-name:
        type: string
    steps:
      - attach_workspace:
            at: ./
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
      - run: ls -R
      - aws-s3/sync:
          arguments: --acl public-read
          from: ./
          overwrite: false
          to: s3://<< parameters.s3-bucket-name >>/<< parameters.destination-path >>
          aws-region: AWS_DEFAULT_REGION

workflows:
  pull-request:
    unless:
      equal: ['trunk', << pipeline.git.branch >>]
    jobs:
      - build-and-unit-test:
          api-url: ${BOOK_A_DESK_BASE_API_URL_DEV}
  release:
    when:
      equal: ['trunk', << pipeline.git.branch >>]
    jobs:
      - build-and-unit-test:
          api-url: ${BOOK_A_DESK_BASE_API_URL_DEV}
      - deploy-cloudformation:
          name: deploy-cloudformation-dev
          authenticate-aws:
            - authenticate-aws-book-a-desk-dev
          update-cdn: false
          s3-bucket-name: << pipeline.parameters.s3-bucket-dev >>
          certificate-id: << pipeline.parameters.acm-certificate-id-dev >>
          environment: dev.
          context:
            - aws-credentials
          requires:
            - build-and-unit-test
      - publish-to-s3:
          name: publish-to-dev
          destination-path: ${CIRCLE_SHA1}
          s3-bucket-name: << pipeline.parameters.s3-bucket-dev >>
          requires:
            - build-and-unit-test
            - deploy-cloudformation-dev
      - deploy-cloudformation:
          name: update-cloudfront-dev
          authenticate-aws:
            - authenticate-aws-book-a-desk-dev
          update-cdn: true
          s3-bucket-name: << pipeline.parameters.s3-bucket-dev >>
          certificate-id: << pipeline.parameters.acm-certificate-id-dev >>
          environment: dev.
          context:
            - aws-credentials
          requires:
            - publish-to-dev
      - deploy-cloudformation:
          name: deploy-cloudformation-test
          authenticate-aws:
            - authenticate-aws-book-a-desk-test
          update-cdn: false
          s3-bucket-name: << pipeline.parameters.s3-bucket-test >>
          certificate-id: << pipeline.parameters.acm-certificate-id-test >>
          environment: dev.
          context:
            - aws-credentials
          requires:
            - update-cloudfron-dev
      - publish-to-s3:
          name: publish-to-test
          destination-path: ${CIRCLE_SHA1}
          s3-bucket-name: << pipeline.parameters.s3-bucket-test >>
          requires:
            - build-and-unit-test
            - deploy-cloudformation-test
      - deploy-cloudformation:
          name: update-cloudfront-test
          authenticate-aws:
            - authenticate-aws-book-a-desk-test
          update-cdn: true
          s3-bucket-name: << pipeline.parameters.s3-bucket-test >>
          certificate-id: << pipeline.parameters.acm-certificate-id-test >>
          environment: test.
          context:
            - aws-credentials
          requires:
            - publish-to-test
#      - build-assets-prod:
#          requires:
#            - publish-to-s3-tes
