version: 2.1

orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.0
  aws-s3: circleci/aws-s3@1.0.16
  
parameters:
  s3-bucket-dev:
      type: string
      default: book-a-desk-ui-2
      
commands:
  authenticate-aws-book-a-desk-dev:
    description: "Configure AWS credentials for Book A Desk Dev"
    steps:
      - run:
          name: "Initialize BASH_ENV variables"
          command: |
            echo "export AWS_ACCESS_KEY_ID=${AWS_DEV_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_DEV_SECRET_ACCESS_KEY}" >> $BASH_ENV
            
  aws-cloudformation-deploy:
    parameters:
      update-cdn:
        type: boolean
        default: false
      authenticate-aws:
        type: steps
      s3-bucket-name:
        type: string
    steps:
      - steps: << parameters.authenticate-aws >>
      - run:
          name: Ensure infrastructure is up to date <<# parameters.update-cdn >>and update the CDN origin<</ parameters.update-cdn >>
          command: |
            aws cloudformation deploy \
              --parameter-overrides "S3Bucket=<< parameters.s3-bucket-name >>" <<# parameters.update-cdn >>"SHA1=${CIRCLE_SHA1}"<</ parameters.update-cdn >> \
              --stack-name book-a-desk-ui \
              --template-file ./infra/cf.yaml \
              --capabilities CAPABILITY_NAMED_IAM
  

jobs:
  build-assets-dev:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: NPM Build Project
          command: |
            export VUE_APP_SHA1=${CIRCLE_SHA1};
            export VUE_APP_BASE_API_URL=${BOOK_A_DESK_BASE_API_URL_DEV}
            npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist/*
              
  build-assets-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: NPM Build Project
          command: |
            export VUE_APP_SHA1=${CIRCLE_SHA1};
            export VUE_APP_BASE_API_URL=${BOOK_A_DESK_BASE_API_URL_TEST}
            npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist/*

  build-assets-prod:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: NPM Build Project
          command: |
            export VUE_APP_SHA1=${CIRCLE_SHA1};
            export VUE_APP_BASE_API_URL=${BOOK_A_DESK_BASE_API_URL_PROD}
            npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist/*

  deploy-cloudformation:
    executor: aws-cli/default
    parameters:
      update-cdn:
        type: boolean
        default: false
      authenticate-aws:
        type: steps
      s3-bucket-name:
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
      - aws-cloudformation-deploy:
          update-cdn: << parameters.update-cdn >>
          authenticate-aws: << parameters.authenticate-aws >>
          s3-bucket-name: << parameters.s3-bucket-name >>
          
  publish-to-s3:
    executor: aws-cli/default
    parameters:
      destination-path:
        type: string
      authenticate-aws:
        type: steps
      s3-bucket-name:
        type: string
    steps:
      - attach_workspace:
          at: ./
      - steps: << parameters.authenticate-aws >>
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
      - run: ls -R
      - aws-s3/sync:
          arguments: --acl public-read --cache-control "public, must-revalidate, max-age=0"
          from: ./
          overwrite: false
          to: s3://<< parameters.s3-bucket-name >>/<< parameters.destination-path >>

  publish-to-s3-dev:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: ./
      - run: ls -R dist/*
      - aws-s3/sync:
          arguments: --acl public-read
          from: ./dist/
          overwrite: false
          to: s3://dev.book-a-desk.broadsign.net/${CIRCLE_SHA1}
          aws-region: AWS_DEFAULT_REGION

  publish-to-s3-test:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: ./
      - run: ls -R dist/*
      - aws-s3/sync:
          arguments: --acl public-read
          from: ./dist/
          overwrite: false
          to: s3://<< pipeline.parameters.s3-bucket >>-Test/${CIRCLE_SHA1}
          aws-region: AWS_DEFAULT_REGION

  publish-to-s3-prod:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: ./
      - run: ls -R dist/*
      - aws-s3/sync:
          arguments: --acl public-read
          from: ./dist/
          overwrite: false
          to: s3://<< pipeline.parameters.s3-bucket >>-Prod/${CIRCLE_SHA1}
          aws-region: AWS_DEFAULT_REGION

workflows:
  node-tests:
    when:
      equal: ['trunk', << pipeline.git.branch >>]
    jobs:
      - node/test
  release:
    unless:
      equal: ['trunk', << pipeline.git.branch >>]
    jobs:
      - node/test
      - build-assets-dev:
          requires:
            - node/test
      - deploy-cloudformation:
          name: deploy-cloudformation-dev
          authenticate-aws:
            - authenticate-aws-book-a-desk-dev
          update-cdn: false
          s3-bucket-name: << pipeline.parameters.s3-bucket-dev >>
          requires:
            - node/test
      - publish-to-s3:
          name: publish-to-dev
          destination-path: ${CIRCLE_SHA1}
          authenticate-aws:
            - authenticate-aws-book-a-desk-dev
          s3-bucket-name: << pipeline.parameters.s3-bucket-dev >>
          requires:
            - build-assets-dev
            - deploy-cloudformation-dev
      - deploy-cloudformation:
          name: update-cloudfront-dev
          authenticate-aws:
            - authenticate-aws-book-a-desk-dev
          update-cdn: true
          s3-bucket-name: << pipeline.parameters.s3-bucket-dev >>
          requires:
            - publish-to-dev
#      - build-assets-test:
#          requires:
#            - publish-to-s3-dev
#      - build-assets-prod:
#          requires:
#            - publish-to-s3-tes
